#!/usr/bin/env ruby

require 'bundler/setup'
require 'mae/server'
require 'mae/project'

case ARGV[0]
when 's', 'server' then
  Mae::Server.start ARGV[1]
when 'new' then
  Mae::Project.create ARGV[1]
end
